# Generated by Django 2.2.5 on 2022-05-07 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=15)),
                ('nombreCliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=40)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('ciudad_id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlProyecto.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('cliente_id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlProyecto.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('precio_producto', models.FloatField()),
                ('cantidad_disponible', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='fecha de publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('estado_envio', models.CharField(choices=[('Despachando', 'Despachando'), ('Enviando', 'Enviando'), ('Entregado', 'Entregado')], max_length=15)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('compra_id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlProyecto.Compra')),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id_descuento', models.AutoField(primary_key=True, serialize=False)),
                ('precio_descuento', models.FloatField()),
                ('estado_descuento', models.BooleanField(default=True, verbose_name='estado')),
                ('producto_id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlProyecto.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento_id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlProyecto.Departamento'),
        ),
        migrations.CreateModel(
            name='Choise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlProyecto.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_carrito', models.IntegerField()),
                ('precio_carrito', models.FloatField()),
                ('compra_id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlProyecto.Compra')),
                ('producto_id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlProyecto.Producto')),
            ],
        ),
    ]
