# Generated by Django 2.2.5 on 2022-05-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlProyecto', '0002_auto_20220507_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='compra_id_compra',
            new_name='compra',
        ),
        migrations.RenameField(
            model_name='carrito',
            old_name='producto_id_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='ciudad',
            old_name='departamento_id_departamento',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='ciudad_id_ciudad',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='cliente_id_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='compra_id_compra',
            new_name='compra',
        ),
    ]
