# Generated by Django 2.2.5 on 2022-05-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlProyecto', '0005_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo_electronico',
            field=models.EmailField(max_length=100),
        ),
    ]
