# Generated by Django 2.2.5 on 2022-06-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlProyecto', '0006_auto_20220518_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
